name: ag_math
description: All Gifted Math
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.2.2
  rive: ^0.13.20
  video_player: ^2.7.2
  lottie: ^3.1.0
  intl: ^0.20.2

  flutter_html: ^3.0.0
  flutter_html_math: ^3.0.0
  flutter_math_fork: ^0.7.4
  flutter_spinbox: ^0.13.1
  flutter_stripe: ^12.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  chewie: ^1.7.0
  in_app_purchase: ^3.1.11  # For future native IAP
  purchases_flutter: ^9.9.0  # RevenueCat (when ready)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/character1.png
    - assets/character2.png
    - assets/logo.png
    - assets/kudo.png
    - assets/animations/octo_diagnostic.json
    - assets/animations/octo2.gif
    - assets/animations/success.json
    - assets/animations/BalloonConfetti.json
    - assets/animations/Fireworks.json
    - assets/animations/Partytoy.json
    - assets/animations/Trophy.json
    - assets/animations/Confetti.json
    - assets/animations/Confetti1.json
    - assets/animations/Correct.json
    - assets/animations/OctopusBalloons.json
    - assets/animations/TaskComplete.json
    - assets/heart.svg
